name: Testing stuff

on:
  push:
    branches:
      - main

env:
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
  CONDITION: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event_name == 'push' && env.CONDITION == 'false' }}
        run: echo "$env.COMMIT_MESSAGES"
